services:
  - type: web
    name: n8n
    env: docker
    plan: free
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: securepass
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
    autoDeploy: true
